//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemetry_ShopApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppsBOBApps
    {
        public tblAppsBOBApps()
        {
            this.tblUsersM2MUserApps = new HashSet<tblUsersM2MUserApps>();
        }
    
        public int id { get; set; }
        public string AppName { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public string ImagePreview1 { get; set; }
        public string ImagePreview2 { get; set; }
        public string ImagePreview3 { get; set; }
        public string ImageShortcut { get; set; }
        public string AppURL { get; set; }
        public Nullable<int> id_Category { get; set; }
        public Nullable<int> counterInstall { get; set; }
        public decimal rate { get; set; }
        public int CoutRated { get; set; }
        public int SumAllRate { get; set; }
    
        public virtual tblAppsBOBCategories tblAppsBOBCategories { get; set; }
        public virtual ICollection<tblUsersM2MUserApps> tblUsersM2MUserApps { get; set; }
        public virtual tblAppsBOBCategories tblAppsBOBCategories1 { get; set; }
    }
}
