//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemetry_ShopApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsersM2MUserApps
    {
        public int id { get; set; }
        public int id_User { get; set; }
        public int id_App { get; set; }
        public bool IsUserRated { get; set; }
    
        public virtual tblAppsBOBApps tblAppsBOBApps { get; set; }
        public virtual Users Users { get; set; }
    }
}
