//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemetry_ShopApps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Telemetry_ShopAppsEntities : DbContext
    {
        public DB_Telemetry_ShopAppsEntities()
            : base("name=DB_Telemetry_ShopAppsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<tblAppsBOBApps> tblAppsBOBApps { get; set; }
        public virtual DbSet<tblAppsBOBCategories> tblAppsBOBCategories { get; set; }
        public virtual DbSet<tblUsersM2MUserApps> tblUsersM2MUserApps { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
