//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemetry_Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyBOBCompany
    {
        public tblCompanyBOBCompany()
        {
            this.tblCompanyBOBPayments = new HashSet<tblCompanyBOBPayments>();
            this.tblUsersBOBUsers = new HashSet<tblUsersBOBUsers>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public decimal CurrentBalance { get; set; }
        public string CompanyUID { get; set; }
    
        public virtual ICollection<tblCompanyBOBPayments> tblCompanyBOBPayments { get; set; }
        public virtual ICollection<tblUsersBOBUsers> tblUsersBOBUsers { get; set; }
    }
}
