//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemetry_Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyBOBPayments
    {
        public System.DateTime DateMessage { get; set; }
        public int id_Company { get; set; }
        public decimal MoneyMove { get; set; }
        public string Comment { get; set; }
    
        public virtual tblCompanyBOBCompany tblCompanyBOBCompany { get; set; }
    }
}
