//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemetry_Users
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Telemetry_UsersEntities : DbContext
    {
        public DB_Telemetry_UsersEntities()
            : base("name=DB_Telemetry_UsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCompanyBOBCompany> tblCompanyBOBCompany { get; set; }
        public virtual DbSet<tblCompanyBOBPayments> tblCompanyBOBPayments { get; set; }
        public virtual DbSet<tblUsersBOBUsers> tblUsersBOBUsers { get; set; }
    }
}
