//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_Telemetry_UsersModel", "tblCompanyBOBCompany_tblUsersBOBUser", "tblCompanyBOBCompany", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AuthEngine.DBAccess.tblCompanyBOBCompany), "tblUsersBOBUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthEngine.DBAccess.tblUsersBOBUsers), true)]
[assembly: EdmRelationshipAttribute("DB_Telemetry_UsersModel", "tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBCompany", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AuthEngine.DBAccess.tblCompanyBOBCompany), "tblCompanyBOBPayments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthEngine.DBAccess.tblCompanyBOBPayments), true)]

#endregion

namespace AuthEngine.DBAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB_Telemetry_UsersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB_Telemetry_UsersEntities object using the connection string found in the 'DB_Telemetry_UsersEntities' section of the application configuration file.
        /// </summary>
        public DB_Telemetry_UsersEntities() : base("name=DB_Telemetry_UsersEntities", "DB_Telemetry_UsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_Telemetry_UsersEntities object.
        /// </summary>
        public DB_Telemetry_UsersEntities(string connectionString) : base(connectionString, "DB_Telemetry_UsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_Telemetry_UsersEntities object.
        /// </summary>
        public DB_Telemetry_UsersEntities(EntityConnection connection) : base(connection, "DB_Telemetry_UsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCompanyBOBCompany> tblCompanyBOBCompany
        {
            get
            {
                if ((_tblCompanyBOBCompany == null))
                {
                    _tblCompanyBOBCompany = base.CreateObjectSet<tblCompanyBOBCompany>("tblCompanyBOBCompany");
                }
                return _tblCompanyBOBCompany;
            }
        }
        private ObjectSet<tblCompanyBOBCompany> _tblCompanyBOBCompany;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUsersBOBUsers> tblUsersBOBUsers
        {
            get
            {
                if ((_tblUsersBOBUsers == null))
                {
                    _tblUsersBOBUsers = base.CreateObjectSet<tblUsersBOBUsers>("tblUsersBOBUsers");
                }
                return _tblUsersBOBUsers;
            }
        }
        private ObjectSet<tblUsersBOBUsers> _tblUsersBOBUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCompanyBOBPayments> tblCompanyBOBPayments
        {
            get
            {
                if ((_tblCompanyBOBPayments == null))
                {
                    _tblCompanyBOBPayments = base.CreateObjectSet<tblCompanyBOBPayments>("tblCompanyBOBPayments");
                }
                return _tblCompanyBOBPayments;
            }
        }
        private ObjectSet<tblCompanyBOBPayments> _tblCompanyBOBPayments;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCompanyBOBCompany EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCompanyBOBCompany(tblCompanyBOBCompany tblCompanyBOBCompany)
        {
            base.AddObject("tblCompanyBOBCompany", tblCompanyBOBCompany);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsersBOBUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsersBOBUsers(tblUsersBOBUsers tblUsersBOBUsers)
        {
            base.AddObject("tblUsersBOBUsers", tblUsersBOBUsers);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCompanyBOBPayments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCompanyBOBPayments(tblCompanyBOBPayments tblCompanyBOBPayments)
        {
            base.AddObject("tblCompanyBOBPayments", tblCompanyBOBPayments);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_Telemetry_UsersModel", Name="tblCompanyBOBCompany")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCompanyBOBCompany : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCompanyBOBCompany object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="currentBalance">Initial value of the CurrentBalance property.</param>
        public static tblCompanyBOBCompany CreatetblCompanyBOBCompany(global::System.Int32 id, global::System.String name, global::System.Decimal currentBalance)
        {
            tblCompanyBOBCompany tblCompanyBOBCompany = new tblCompanyBOBCompany();
            tblCompanyBOBCompany.id = id;
            tblCompanyBOBCompany.Name = name;
            tblCompanyBOBCompany.CurrentBalance = currentBalance;
            return tblCompanyBOBCompany;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CurrentBalance
        {
            get
            {
                return _CurrentBalance;
            }
            set
            {
                OnCurrentBalanceChanging(value);
                ReportPropertyChanging("CurrentBalance");
                _CurrentBalance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentBalance");
                OnCurrentBalanceChanged();
            }
        }
        private global::System.Decimal _CurrentBalance;
        partial void OnCurrentBalanceChanging(global::System.Decimal value);
        partial void OnCurrentBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyUID
        {
            get
            {
                return _CompanyUID;
            }
            set
            {
                OnCompanyUIDChanging(value);
                ReportPropertyChanging("CompanyUID");
                _CompanyUID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyUID");
                OnCompanyUIDChanged();
            }
        }
        private global::System.String _CompanyUID;
        partial void OnCompanyUIDChanging(global::System.String value);
        partial void OnCompanyUIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_Telemetry_UsersModel", "tblCompanyBOBCompany_tblUsersBOBUser", "tblUsersBOBUsers")]
        public EntityCollection<tblUsersBOBUsers> tblUsersBOBUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblUsersBOBUsers>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblUsersBOBUser", "tblUsersBOBUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblUsersBOBUsers>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblUsersBOBUser", "tblUsersBOBUsers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_Telemetry_UsersModel", "tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBPayments")]
        public EntityCollection<tblCompanyBOBPayments> tblCompanyBOBPayments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblCompanyBOBPayments>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBPayments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblCompanyBOBPayments>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBPayments", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_Telemetry_UsersModel", Name="tblCompanyBOBPayments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCompanyBOBPayments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCompanyBOBPayments object.
        /// </summary>
        /// <param name="dateMessage">Initial value of the DateMessage property.</param>
        /// <param name="id_Company">Initial value of the id_Company property.</param>
        /// <param name="moneyMove">Initial value of the MoneyMove property.</param>
        public static tblCompanyBOBPayments CreatetblCompanyBOBPayments(global::System.DateTime dateMessage, global::System.Int32 id_Company, global::System.Decimal moneyMove)
        {
            tblCompanyBOBPayments tblCompanyBOBPayments = new tblCompanyBOBPayments();
            tblCompanyBOBPayments.DateMessage = dateMessage;
            tblCompanyBOBPayments.id_Company = id_Company;
            tblCompanyBOBPayments.MoneyMove = moneyMove;
            return tblCompanyBOBPayments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateMessage
        {
            get
            {
                return _DateMessage;
            }
            set
            {
                if (_DateMessage != value)
                {
                    OnDateMessageChanging(value);
                    ReportPropertyChanging("DateMessage");
                    _DateMessage = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateMessage");
                    OnDateMessageChanged();
                }
            }
        }
        private global::System.DateTime _DateMessage;
        partial void OnDateMessageChanging(global::System.DateTime value);
        partial void OnDateMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Company
        {
            get
            {
                return _id_Company;
            }
            set
            {
                Onid_CompanyChanging(value);
                ReportPropertyChanging("id_Company");
                _id_Company = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_Company");
                Onid_CompanyChanged();
            }
        }
        private global::System.Int32 _id_Company;
        partial void Onid_CompanyChanging(global::System.Int32 value);
        partial void Onid_CompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MoneyMove
        {
            get
            {
                return _MoneyMove;
            }
            set
            {
                OnMoneyMoveChanging(value);
                ReportPropertyChanging("MoneyMove");
                _MoneyMove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MoneyMove");
                OnMoneyMoveChanged();
            }
        }
        private global::System.Decimal _MoneyMove;
        partial void OnMoneyMoveChanging(global::System.Decimal value);
        partial void OnMoneyMoveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_Telemetry_UsersModel", "tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBCompany")]
        public tblCompanyBOBCompany tblCompanyBOBCompany
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCompanyBOBCompany>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBCompany").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCompanyBOBCompany>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBCompany").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCompanyBOBCompany> tblCompanyBOBCompanyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCompanyBOBCompany>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBCompany");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCompanyBOBCompany>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblCompanyBOBPayment", "tblCompanyBOBCompany", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_Telemetry_UsersModel", Name="tblUsersBOBUsers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUsersBOBUsers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUsersBOBUsers object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="solt">Initial value of the Solt property.</param>
        /// <param name="mail">Initial value of the Mail property.</param>
        /// <param name="id_Company">Initial value of the id_Company property.</param>
        /// <param name="password1">Initial value of the Password1 property.</param>
        /// <param name="gUID">Initial value of the GUID property.</param>
        /// <param name="isAdmin">Initial value of the isAdmin property.</param>
        /// <param name="isSubmit">Initial value of the isSubmit property.</param>
        public static tblUsersBOBUsers CreatetblUsersBOBUsers(global::System.Int32 id, global::System.String name, global::System.String login, global::System.String password, global::System.String solt, global::System.String mail, global::System.Int32 id_Company, global::System.String password1, global::System.String gUID, global::System.Boolean isAdmin, global::System.Boolean isSubmit)
        {
            tblUsersBOBUsers tblUsersBOBUsers = new tblUsersBOBUsers();
            tblUsersBOBUsers.id = id;
            tblUsersBOBUsers.Name = name;
            tblUsersBOBUsers.Login = login;
            tblUsersBOBUsers.Password = password;
            tblUsersBOBUsers.Solt = solt;
            tblUsersBOBUsers.Mail = mail;
            tblUsersBOBUsers.id_Company = id_Company;
            tblUsersBOBUsers.Password1 = password1;
            tblUsersBOBUsers.GUID = gUID;
            tblUsersBOBUsers.isAdmin = isAdmin;
            tblUsersBOBUsers.isSubmit = isSubmit;
            return tblUsersBOBUsers;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Solt
        {
            get
            {
                return _Solt;
            }
            set
            {
                OnSoltChanging(value);
                ReportPropertyChanging("Solt");
                _Solt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Solt");
                OnSoltChanged();
            }
        }
        private global::System.String _Solt;
        partial void OnSoltChanging(global::System.String value);
        partial void OnSoltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Company
        {
            get
            {
                return _id_Company;
            }
            set
            {
                Onid_CompanyChanging(value);
                ReportPropertyChanging("id_Company");
                _id_Company = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_Company");
                Onid_CompanyChanged();
            }
        }
        private global::System.Int32 _id_Company;
        partial void Onid_CompanyChanging(global::System.Int32 value);
        partial void Onid_CompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password1
        {
            get
            {
                return _Password1;
            }
            set
            {
                OnPassword1Changing(value);
                ReportPropertyChanging("Password1");
                _Password1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password1");
                OnPassword1Changed();
            }
        }
        private global::System.String _Password1;
        partial void OnPassword1Changing(global::System.String value);
        partial void OnPassword1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                OnGUIDChanging(value);
                ReportPropertyChanging("GUID");
                _GUID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GUID");
                OnGUIDChanged();
            }
        }
        private global::System.String _GUID;
        partial void OnGUIDChanging(global::System.String value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isAdmin
        {
            get
            {
                return _isAdmin;
            }
            set
            {
                OnisAdminChanging(value);
                ReportPropertyChanging("isAdmin");
                _isAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isAdmin");
                OnisAdminChanged();
            }
        }
        private global::System.Boolean _isAdmin;
        partial void OnisAdminChanging(global::System.Boolean value);
        partial void OnisAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isSubmit
        {
            get
            {
                return _isSubmit;
            }
            set
            {
                OnisSubmitChanging(value);
                ReportPropertyChanging("isSubmit");
                _isSubmit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isSubmit");
                OnisSubmitChanged();
            }
        }
        private global::System.Boolean _isSubmit;
        partial void OnisSubmitChanging(global::System.Boolean value);
        partial void OnisSubmitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isCompanyAdmin
        {
            get
            {
                return _isCompanyAdmin;
            }
            set
            {
                OnisCompanyAdminChanging(value);
                ReportPropertyChanging("isCompanyAdmin");
                _isCompanyAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isCompanyAdmin");
                OnisCompanyAdminChanged();
            }
        }
        private Nullable<global::System.Boolean> _isCompanyAdmin;
        partial void OnisCompanyAdminChanging(Nullable<global::System.Boolean> value);
        partial void OnisCompanyAdminChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_Telemetry_UsersModel", "tblCompanyBOBCompany_tblUsersBOBUser", "tblCompanyBOBCompany")]
        public tblCompanyBOBCompany tblCompanyBOBCompany
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCompanyBOBCompany>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblUsersBOBUser", "tblCompanyBOBCompany").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCompanyBOBCompany>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblUsersBOBUser", "tblCompanyBOBCompany").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCompanyBOBCompany> tblCompanyBOBCompanyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCompanyBOBCompany>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblUsersBOBUser", "tblCompanyBOBCompany");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCompanyBOBCompany>("DB_Telemetry_UsersModel.tblCompanyBOBCompany_tblUsersBOBUser", "tblCompanyBOBCompany", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
