//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopEngine.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public int id_User { get; set; }
        public int id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
