//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopEngine.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int RevID { get; set; }
        public string bylogin { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
        public int id_App { get; set; }
    }
}
