//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34003.
// 
#pragma warning disable 1591

namespace Test_tmtLauncher.ServiceLayer.LauncherWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tmtLauncherWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class tmtLauncherWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOnOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOffOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakeSomeActionOperationCompleted;
        
        private System.Threading.SendOrPostCallback APPS_GetAppsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback APPS_GetUserAppsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDownloadedFileInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDownloadedFileChunkOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDownloadedFileCRC32HashOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InstallApplicationForUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UninstallApplicationForUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShopApplicationsInfoForCustomUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInstalledApplicationsInfoForCustomUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllApplicationsInfoForCustomUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tmtLauncherWebService() {
            this.Url = global::Test_tmtLauncher.ServiceLayer.Properties.Settings.Default.Test_for_SecurityCommunicationEngine_LauncherWebService_tmtLauncherWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterNewUserCompletedEventHandler RegisterNewUserCompleted;
        
        /// <remarks/>
        public event LogOnCompletedEventHandler LogOnCompleted;
        
        /// <remarks/>
        public event LogOffCompletedEventHandler LogOffCompleted;
        
        /// <remarks/>
        public event MakeSomeActionCompletedEventHandler MakeSomeActionCompleted;
        
        /// <remarks/>
        public event APPS_GetAppsListCompletedEventHandler APPS_GetAppsListCompleted;
        
        /// <remarks/>
        public event APPS_GetUserAppsCompletedEventHandler APPS_GetUserAppsCompleted;
        
        /// <remarks/>
        public event GetDownloadedFileInfoCompletedEventHandler GetDownloadedFileInfoCompleted;
        
        /// <remarks/>
        public event GetDownloadedFileChunkCompletedEventHandler GetDownloadedFileChunkCompleted;
        
        /// <remarks/>
        public event GetDownloadedFileCRC32HashCompletedEventHandler GetDownloadedFileCRC32HashCompleted;
        
        /// <remarks/>
        public event GetAppInfoCompletedEventHandler GetAppInfoCompleted;
        
        /// <remarks/>
        public event InstallApplicationForUserCompletedEventHandler InstallApplicationForUserCompleted;
        
        /// <remarks/>
        public event UninstallApplicationForUserCompletedEventHandler UninstallApplicationForUserCompleted;
        
        /// <remarks/>
        public event GetShopApplicationsInfoForCustomUserCompletedEventHandler GetShopApplicationsInfoForCustomUserCompleted;
        
        /// <remarks/>
        public event GetInstalledApplicationsInfoForCustomUserCompletedEventHandler GetInstalledApplicationsInfoForCustomUserCompleted;
        
        /// <remarks/>
        public event GetAllApplicationsInfoForCustomUserCompletedEventHandler GetAllApplicationsInfoForCustomUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterNewUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisterNewUser(UserRegistrationInfo regInfo) {
            object[] results = this.Invoke("RegisterNewUser", new object[] {
                        regInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterNewUserAsync(UserRegistrationInfo regInfo) {
            this.RegisterNewUserAsync(regInfo, null);
        }
        
        /// <remarks/>
        public void RegisterNewUserAsync(UserRegistrationInfo regInfo, object userState) {
            if ((this.RegisterNewUserOperationCompleted == null)) {
                this.RegisterNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterNewUserOperationCompleted);
            }
            this.InvokeAsync("RegisterNewUser", new object[] {
                        regInfo}, this.RegisterNewUserOperationCompleted, userState);
        }
        
        private void OnRegisterNewUserOperationCompleted(object arg) {
            if ((this.RegisterNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterNewUserCompleted(this, new RegisterNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Token LogOn(string login, string password, out int currUserId) {
            object[] results = this.Invoke("LogOn", new object[] {
                        login,
                        password});
            currUserId = ((int)(results[1]));
            return ((Token)(results[0]));
        }
        
        /// <remarks/>
        public void LogOnAsync(string login, string password) {
            this.LogOnAsync(login, password, null);
        }
        
        /// <remarks/>
        public void LogOnAsync(string login, string password, object userState) {
            if ((this.LogOnOperationCompleted == null)) {
                this.LogOnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOnOperationCompleted);
            }
            this.InvokeAsync("LogOn", new object[] {
                        login,
                        password}, this.LogOnOperationCompleted, userState);
        }
        
        private void OnLogOnOperationCompleted(object arg) {
            if ((this.LogOnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOnCompleted(this, new LogOnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOff", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogOff() {
            this.Invoke("LogOff", new object[0]);
        }
        
        /// <remarks/>
        public void LogOffAsync() {
            this.LogOffAsync(null);
        }
        
        /// <remarks/>
        public void LogOffAsync(object userState) {
            if ((this.LogOffOperationCompleted == null)) {
                this.LogOffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOffOperationCompleted);
            }
            this.InvokeAsync("LogOff", new object[0], this.LogOffOperationCompleted, userState);
        }
        
        private void OnLogOffOperationCompleted(object arg) {
            if ((this.LogOffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOffCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MakeSomeAction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MakeSomeAction(Token st, int param1) {
            object[] results = this.Invoke("MakeSomeAction", new object[] {
                        st,
                        param1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MakeSomeActionAsync(Token st, int param1) {
            this.MakeSomeActionAsync(st, param1, null);
        }
        
        /// <remarks/>
        public void MakeSomeActionAsync(Token st, int param1, object userState) {
            if ((this.MakeSomeActionOperationCompleted == null)) {
                this.MakeSomeActionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakeSomeActionOperationCompleted);
            }
            this.InvokeAsync("MakeSomeAction", new object[] {
                        st,
                        param1}, this.MakeSomeActionOperationCompleted, userState);
        }
        
        private void OnMakeSomeActionOperationCompleted(object arg) {
            if ((this.MakeSomeActionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakeSomeActionCompleted(this, new MakeSomeActionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/APPS_GetAppsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppsDataModel[] APPS_GetAppsList(Token st) {
            object[] results = this.Invoke("APPS_GetAppsList", new object[] {
                        st});
            return ((AppsDataModel[])(results[0]));
        }
        
        /// <remarks/>
        public void APPS_GetAppsListAsync(Token st) {
            this.APPS_GetAppsListAsync(st, null);
        }
        
        /// <remarks/>
        public void APPS_GetAppsListAsync(Token st, object userState) {
            if ((this.APPS_GetAppsListOperationCompleted == null)) {
                this.APPS_GetAppsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAPPS_GetAppsListOperationCompleted);
            }
            this.InvokeAsync("APPS_GetAppsList", new object[] {
                        st}, this.APPS_GetAppsListOperationCompleted, userState);
        }
        
        private void OnAPPS_GetAppsListOperationCompleted(object arg) {
            if ((this.APPS_GetAppsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.APPS_GetAppsListCompleted(this, new APPS_GetAppsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/APPS_GetUserApps", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppsDataModel[] APPS_GetUserApps(Token st) {
            object[] results = this.Invoke("APPS_GetUserApps", new object[] {
                        st});
            return ((AppsDataModel[])(results[0]));
        }
        
        /// <remarks/>
        public void APPS_GetUserAppsAsync(Token st) {
            this.APPS_GetUserAppsAsync(st, null);
        }
        
        /// <remarks/>
        public void APPS_GetUserAppsAsync(Token st, object userState) {
            if ((this.APPS_GetUserAppsOperationCompleted == null)) {
                this.APPS_GetUserAppsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAPPS_GetUserAppsOperationCompleted);
            }
            this.InvokeAsync("APPS_GetUserApps", new object[] {
                        st}, this.APPS_GetUserAppsOperationCompleted, userState);
        }
        
        private void OnAPPS_GetUserAppsOperationCompleted(object arg) {
            if ((this.APPS_GetUserAppsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.APPS_GetUserAppsCompleted(this, new APPS_GetUserAppsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDownloadedFileInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileInfo GetDownloadedFileInfo(Token st, string fileName) {
            object[] results = this.Invoke("GetDownloadedFileInfo", new object[] {
                        st,
                        fileName});
            return ((FileInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetDownloadedFileInfoAsync(Token st, string fileName) {
            this.GetDownloadedFileInfoAsync(st, fileName, null);
        }
        
        /// <remarks/>
        public void GetDownloadedFileInfoAsync(Token st, string fileName, object userState) {
            if ((this.GetDownloadedFileInfoOperationCompleted == null)) {
                this.GetDownloadedFileInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDownloadedFileInfoOperationCompleted);
            }
            this.InvokeAsync("GetDownloadedFileInfo", new object[] {
                        st,
                        fileName}, this.GetDownloadedFileInfoOperationCompleted, userState);
        }
        
        private void OnGetDownloadedFileInfoOperationCompleted(object arg) {
            if ((this.GetDownloadedFileInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDownloadedFileInfoCompleted(this, new GetDownloadedFileInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDownloadedFileChunk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChunkInfo GetDownloadedFileChunk(Token st, string fileName, long chunkNumber) {
            object[] results = this.Invoke("GetDownloadedFileChunk", new object[] {
                        st,
                        fileName,
                        chunkNumber});
            return ((ChunkInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetDownloadedFileChunkAsync(Token st, string fileName, long chunkNumber) {
            this.GetDownloadedFileChunkAsync(st, fileName, chunkNumber, null);
        }
        
        /// <remarks/>
        public void GetDownloadedFileChunkAsync(Token st, string fileName, long chunkNumber, object userState) {
            if ((this.GetDownloadedFileChunkOperationCompleted == null)) {
                this.GetDownloadedFileChunkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDownloadedFileChunkOperationCompleted);
            }
            this.InvokeAsync("GetDownloadedFileChunk", new object[] {
                        st,
                        fileName,
                        chunkNumber}, this.GetDownloadedFileChunkOperationCompleted, userState);
        }
        
        private void OnGetDownloadedFileChunkOperationCompleted(object arg) {
            if ((this.GetDownloadedFileChunkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDownloadedFileChunkCompleted(this, new GetDownloadedFileChunkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDownloadedFileCRC32Hash", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public uint GetDownloadedFileCRC32Hash(Token st, string fileName) {
            object[] results = this.Invoke("GetDownloadedFileCRC32Hash", new object[] {
                        st,
                        fileName});
            return ((uint)(results[0]));
        }
        
        /// <remarks/>
        public void GetDownloadedFileCRC32HashAsync(Token st, string fileName) {
            this.GetDownloadedFileCRC32HashAsync(st, fileName, null);
        }
        
        /// <remarks/>
        public void GetDownloadedFileCRC32HashAsync(Token st, string fileName, object userState) {
            if ((this.GetDownloadedFileCRC32HashOperationCompleted == null)) {
                this.GetDownloadedFileCRC32HashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDownloadedFileCRC32HashOperationCompleted);
            }
            this.InvokeAsync("GetDownloadedFileCRC32Hash", new object[] {
                        st,
                        fileName}, this.GetDownloadedFileCRC32HashOperationCompleted, userState);
        }
        
        private void OnGetDownloadedFileCRC32HashOperationCompleted(object arg) {
            if ((this.GetDownloadedFileCRC32HashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDownloadedFileCRC32HashCompleted(this, new GetDownloadedFileCRC32HashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAppInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppsDataModel GetAppInfo(Token st, int AppID) {
            object[] results = this.Invoke("GetAppInfo", new object[] {
                        st,
                        AppID});
            return ((AppsDataModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetAppInfoAsync(Token st, int AppID) {
            this.GetAppInfoAsync(st, AppID, null);
        }
        
        /// <remarks/>
        public void GetAppInfoAsync(Token st, int AppID, object userState) {
            if ((this.GetAppInfoOperationCompleted == null)) {
                this.GetAppInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppInfoOperationCompleted);
            }
            this.InvokeAsync("GetAppInfo", new object[] {
                        st,
                        AppID}, this.GetAppInfoOperationCompleted, userState);
        }
        
        private void OnGetAppInfoOperationCompleted(object arg) {
            if ((this.GetAppInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppInfoCompleted(this, new GetAppInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InstallApplicationForUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InstallApplicationForUser(Token st, int userId, int appId) {
            this.Invoke("InstallApplicationForUser", new object[] {
                        st,
                        userId,
                        appId});
        }
        
        /// <remarks/>
        public void InstallApplicationForUserAsync(Token st, int userId, int appId) {
            this.InstallApplicationForUserAsync(st, userId, appId, null);
        }
        
        /// <remarks/>
        public void InstallApplicationForUserAsync(Token st, int userId, int appId, object userState) {
            if ((this.InstallApplicationForUserOperationCompleted == null)) {
                this.InstallApplicationForUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInstallApplicationForUserOperationCompleted);
            }
            this.InvokeAsync("InstallApplicationForUser", new object[] {
                        st,
                        userId,
                        appId}, this.InstallApplicationForUserOperationCompleted, userState);
        }
        
        private void OnInstallApplicationForUserOperationCompleted(object arg) {
            if ((this.InstallApplicationForUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InstallApplicationForUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UninstallApplicationForUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UninstallApplicationForUser(Token st, int userId, int appId) {
            this.Invoke("UninstallApplicationForUser", new object[] {
                        st,
                        userId,
                        appId});
        }
        
        /// <remarks/>
        public void UninstallApplicationForUserAsync(Token st, int userId, int appId) {
            this.UninstallApplicationForUserAsync(st, userId, appId, null);
        }
        
        /// <remarks/>
        public void UninstallApplicationForUserAsync(Token st, int userId, int appId, object userState) {
            if ((this.UninstallApplicationForUserOperationCompleted == null)) {
                this.UninstallApplicationForUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUninstallApplicationForUserOperationCompleted);
            }
            this.InvokeAsync("UninstallApplicationForUser", new object[] {
                        st,
                        userId,
                        appId}, this.UninstallApplicationForUserOperationCompleted, userState);
        }
        
        private void OnUninstallApplicationForUserOperationCompleted(object arg) {
            if ((this.UninstallApplicationForUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UninstallApplicationForUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShopApplicationsInfoForCustomUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppsDataModel[] GetShopApplicationsInfoForCustomUser(Token st, int userId) {
            object[] results = this.Invoke("GetShopApplicationsInfoForCustomUser", new object[] {
                        st,
                        userId});
            return ((AppsDataModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShopApplicationsInfoForCustomUserAsync(Token st, int userId) {
            this.GetShopApplicationsInfoForCustomUserAsync(st, userId, null);
        }
        
        /// <remarks/>
        public void GetShopApplicationsInfoForCustomUserAsync(Token st, int userId, object userState) {
            if ((this.GetShopApplicationsInfoForCustomUserOperationCompleted == null)) {
                this.GetShopApplicationsInfoForCustomUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShopApplicationsInfoForCustomUserOperationCompleted);
            }
            this.InvokeAsync("GetShopApplicationsInfoForCustomUser", new object[] {
                        st,
                        userId}, this.GetShopApplicationsInfoForCustomUserOperationCompleted, userState);
        }
        
        private void OnGetShopApplicationsInfoForCustomUserOperationCompleted(object arg) {
            if ((this.GetShopApplicationsInfoForCustomUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShopApplicationsInfoForCustomUserCompleted(this, new GetShopApplicationsInfoForCustomUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInstalledApplicationsInfoForCustomUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppsDataModel[] GetInstalledApplicationsInfoForCustomUser(Token st, int userId) {
            object[] results = this.Invoke("GetInstalledApplicationsInfoForCustomUser", new object[] {
                        st,
                        userId});
            return ((AppsDataModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInstalledApplicationsInfoForCustomUserAsync(Token st, int userId) {
            this.GetInstalledApplicationsInfoForCustomUserAsync(st, userId, null);
        }
        
        /// <remarks/>
        public void GetInstalledApplicationsInfoForCustomUserAsync(Token st, int userId, object userState) {
            if ((this.GetInstalledApplicationsInfoForCustomUserOperationCompleted == null)) {
                this.GetInstalledApplicationsInfoForCustomUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInstalledApplicationsInfoForCustomUserOperationCompleted);
            }
            this.InvokeAsync("GetInstalledApplicationsInfoForCustomUser", new object[] {
                        st,
                        userId}, this.GetInstalledApplicationsInfoForCustomUserOperationCompleted, userState);
        }
        
        private void OnGetInstalledApplicationsInfoForCustomUserOperationCompleted(object arg) {
            if ((this.GetInstalledApplicationsInfoForCustomUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInstalledApplicationsInfoForCustomUserCompleted(this, new GetInstalledApplicationsInfoForCustomUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllApplicationsInfoForCustomUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppsDataModel[] GetAllApplicationsInfoForCustomUser(Token st, int userId) {
            object[] results = this.Invoke("GetAllApplicationsInfoForCustomUser", new object[] {
                        st,
                        userId});
            return ((AppsDataModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllApplicationsInfoForCustomUserAsync(Token st, int userId) {
            this.GetAllApplicationsInfoForCustomUserAsync(st, userId, null);
        }
        
        /// <remarks/>
        public void GetAllApplicationsInfoForCustomUserAsync(Token st, int userId, object userState) {
            if ((this.GetAllApplicationsInfoForCustomUserOperationCompleted == null)) {
                this.GetAllApplicationsInfoForCustomUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllApplicationsInfoForCustomUserOperationCompleted);
            }
            this.InvokeAsync("GetAllApplicationsInfoForCustomUser", new object[] {
                        st,
                        userId}, this.GetAllApplicationsInfoForCustomUserOperationCompleted, userState);
        }
        
        private void OnGetAllApplicationsInfoForCustomUserOperationCompleted(object arg) {
            if ((this.GetAllApplicationsInfoForCustomUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllApplicationsInfoForCustomUserCompleted(this, new GetAllApplicationsInfoForCustomUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserRegistrationInfo {
        
        private User userField;
        
        private Company usersCompanyField;
        
        /// <remarks/>
        public User user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public Company usersCompany {
            get {
                return this.usersCompanyField;
            }
            set {
                this.usersCompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private int idField;
        
        private string nameField;
        
        private string loginField;
        
        private string passwordField;
        
        private string soltField;
        
        private string mailField;
        
        private string phoneField;
        
        private int id_CompanyField;
        
        private string password1Field;
        
        private System.Guid gUIDField;
        
        private bool isAdminField;
        
        private bool isSubmitField;
        
        private System.Nullable<bool> isCompanyAdminField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Solt {
            get {
                return this.soltField;
            }
            set {
                this.soltField = value;
            }
        }
        
        /// <remarks/>
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public int id_Company {
            get {
                return this.id_CompanyField;
            }
            set {
                this.id_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public string Password1 {
            get {
                return this.password1Field;
            }
            set {
                this.password1Field = value;
            }
        }
        
        /// <remarks/>
        public System.Guid GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
            }
        }
        
        /// <remarks/>
        public bool isSubmit {
            get {
                return this.isSubmitField;
            }
            set {
                this.isSubmitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isCompanyAdmin {
            get {
                return this.isCompanyAdminField;
            }
            set {
                this.isCompanyAdminField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChunkInfo {
        
        private long currChunkNumberField;
        
        private long currChunkSizeField;
        
        private byte[] chunkDataField;
        
        /// <remarks/>
        public long CurrChunkNumber {
            get {
                return this.currChunkNumberField;
            }
            set {
                this.currChunkNumberField = value;
            }
        }
        
        /// <remarks/>
        public long CurrChunkSize {
            get {
                return this.currChunkSizeField;
            }
            set {
                this.currChunkSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ChunkData {
            get {
                return this.chunkDataField;
            }
            set {
                this.chunkDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileInfo {
        
        private string filesToDownloadPathField;
        
        private string fileNameField;
        
        private long fileSizeField;
        
        private long chunkSizeField;
        
        private long chunkCountField;
        
        /// <remarks/>
        public string FilesToDownloadPath {
            get {
                return this.filesToDownloadPathField;
            }
            set {
                this.filesToDownloadPathField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public long FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        public long ChunkSize {
            get {
                return this.chunkSizeField;
            }
            set {
                this.chunkSizeField = value;
            }
        }
        
        /// <remarks/>
        public long ChunkCount {
            get {
                return this.chunkCountField;
            }
            set {
                this.chunkCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AppsDataModel {
        
        private int appIDField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string appShortcutField;
        
        private string banner250x250URLField;
        
        private string banner100x100URLField;
        
        private string screenshotsURLField;
        
        private string actualFileNameField;
        
        private string iconField;
        
        private int counterInstallField;
        
        private int iD_categoryField;
        
        private string categoryNameField;
        
        private decimal rateField;
        
        private int screenshotsCountField;
        
        private double actualVersionField;
        
        private bool isSetupRequiredField;
        
        private bool isUpdateRequiredField;
        
        private double installedVersionField;
        
        private decimal currUserRateField;
        
        /// <remarks/>
        public int AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string AppShortcut {
            get {
                return this.appShortcutField;
            }
            set {
                this.appShortcutField = value;
            }
        }
        
        /// <remarks/>
        public string Banner250x250URL {
            get {
                return this.banner250x250URLField;
            }
            set {
                this.banner250x250URLField = value;
            }
        }
        
        /// <remarks/>
        public string Banner100x100URL {
            get {
                return this.banner100x100URLField;
            }
            set {
                this.banner100x100URLField = value;
            }
        }
        
        /// <remarks/>
        public string ScreenshotsURL {
            get {
                return this.screenshotsURLField;
            }
            set {
                this.screenshotsURLField = value;
            }
        }
        
        /// <remarks/>
        public string ActualFileName {
            get {
                return this.actualFileNameField;
            }
            set {
                this.actualFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public int counterInstall {
            get {
                return this.counterInstallField;
            }
            set {
                this.counterInstallField = value;
            }
        }
        
        /// <remarks/>
        public int ID_category {
            get {
                return this.iD_categoryField;
            }
            set {
                this.iD_categoryField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public int ScreenshotsCount {
            get {
                return this.screenshotsCountField;
            }
            set {
                this.screenshotsCountField = value;
            }
        }
        
        /// <remarks/>
        public double ActualVersion {
            get {
                return this.actualVersionField;
            }
            set {
                this.actualVersionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSetupRequired {
            get {
                return this.isSetupRequiredField;
            }
            set {
                this.isSetupRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsUpdateRequired {
            get {
                return this.isUpdateRequiredField;
            }
            set {
                this.isUpdateRequiredField = value;
            }
        }
        
        /// <remarks/>
        public double InstalledVersion {
            get {
                return this.installedVersionField;
            }
            set {
                this.installedVersionField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurrUserRate {
            get {
                return this.currUserRateField;
            }
            set {
                this.currUserRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Token {
        
        private System.Guid internalDataField;
        
        private System.Guid internalDataUField;
        
        /// <remarks/>
        public System.Guid internalData {
            get {
                return this.internalDataField;
            }
            set {
                this.internalDataField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid internalDataU {
            get {
                return this.internalDataUField;
            }
            set {
                this.internalDataUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Company {
        
        private int idField;
        
        private string nameField;
        
        private string adressField;
        
        private decimal currentBalanceField;
        
        private System.Guid companyUIDField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Adress {
            get {
                return this.adressField;
            }
            set {
                this.adressField = value;
            }
        }
        
        /// <remarks/>
        public decimal CurrentBalance {
            get {
                return this.currentBalanceField;
            }
            set {
                this.currentBalanceField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CompanyUID {
            get {
                return this.companyUIDField;
            }
            set {
                this.companyUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RegisterNewUserCompletedEventHandler(object sender, RegisterNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LogOnCompletedEventHandler(object sender, LogOnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogOnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogOnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Token Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Token)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int currUserId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void LogOffCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void MakeSomeActionCompletedEventHandler(object sender, MakeSomeActionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakeSomeActionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakeSomeActionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void APPS_GetAppsListCompletedEventHandler(object sender, APPS_GetAppsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class APPS_GetAppsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal APPS_GetAppsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AppsDataModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AppsDataModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void APPS_GetUserAppsCompletedEventHandler(object sender, APPS_GetUserAppsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class APPS_GetUserAppsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal APPS_GetUserAppsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AppsDataModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AppsDataModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDownloadedFileInfoCompletedEventHandler(object sender, GetDownloadedFileInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDownloadedFileInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDownloadedFileInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDownloadedFileChunkCompletedEventHandler(object sender, GetDownloadedFileChunkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDownloadedFileChunkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDownloadedFileChunkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChunkInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChunkInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDownloadedFileCRC32HashCompletedEventHandler(object sender, GetDownloadedFileCRC32HashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDownloadedFileCRC32HashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDownloadedFileCRC32HashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAppInfoCompletedEventHandler(object sender, GetAppInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AppsDataModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AppsDataModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void InstallApplicationForUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UninstallApplicationForUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetShopApplicationsInfoForCustomUserCompletedEventHandler(object sender, GetShopApplicationsInfoForCustomUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShopApplicationsInfoForCustomUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShopApplicationsInfoForCustomUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AppsDataModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AppsDataModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetInstalledApplicationsInfoForCustomUserCompletedEventHandler(object sender, GetInstalledApplicationsInfoForCustomUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInstalledApplicationsInfoForCustomUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInstalledApplicationsInfoForCustomUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AppsDataModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AppsDataModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllApplicationsInfoForCustomUserCompletedEventHandler(object sender, GetAllApplicationsInfoForCustomUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllApplicationsInfoForCustomUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllApplicationsInfoForCustomUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AppsDataModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AppsDataModel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591